/* ═══════════════════════════════════════════════════
   PROJECTS DATA — All 24 projects by Urban Grid
   Each project: name, category, location, area, client,
   type, status, role, image URL, summary
═══════════════════════════════════════════════════ */
const PROJECTS = [
    {
        name: "PAVANI MIRABILIA",
        category: "residential",
        location: "Bangalore",
        area: "13 Acres",
        client: "Pavani Group",
        type: "Residential Group Housing",
        status: "Completed",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/projects/PAVANI MIRABILIA Bangalore.webp",
        summary: "A 13-acre residential township featuring multiple towers with modern design language, extensive landscape zones, and community-centric amenities."
    },
    {
        name: "DSR THE ADDRESS",
        category: "residential",
        location: "Bangalore",
        area: "26 Acres",
        client: "DSR Infra Pvt. Ltd.",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "Images for Portfolio/DSR THE ADDRESS Bangalore.png",
        summary: "A sprawling 26-acre mega residential township by DSR Infra featuring multiple towers, extensive landscape and amenity zones, and a self-contained urban ecosystem."
    },
    {
        name: "Purva Zenium",
        category: "residential",
        location: "International Airport Road, North Bangalore",
        area: "11,25,769 Sq. Ft.",
        client: "Puravankara",
        type: "Group Housing: Highrise Apartment",
        status: "Under Construction",
        role: "Concept Construction stage Associate Director - KIPL",
        image: "images/projects/Purva Zenium.png",
        summary: "A next-generation BluNex intelligent-home community by Puravankara on 10.05 acres, integrating IoT-based automation, oxygen-infused clubhouse design, and tropical landscaping."
    },
    {
        name: "Highland Greenz",
        category: "residential",
        location: "Bangalore",
        area: "10 Acres",
        client: "DSR Infra Pvt. Ltd.",
        type: "Residential Group Housing",
        status: "Completed",
        role: "Concept to Construction Stage Director - GPPL",
        image: "Images for Portfolio/Highland Greenz Bangalore.webp",
        summary: "A 10-acre green-themed residential development emphasizing sustainable design, efficient space planning, and lush landscaping for healthy community living."
    },
    {
        name: "Provident Tree",
        category: "residential",
        location: "off Magadi Road, West Bengaluru",
        area: "6,73,647 Sq. Ft.",
        client: "Provident Housing Ltd.",
        type: "Group Housing: Highrise Apartment",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/projects/Provident Tree.png",
        summary: "A 6-acre green-themed development designed around 330+ preserved trees, featuring 560 eco-centric homes with 80% open space and natural ventilation."
    },
    {
        name: "Adora-De-Goa",
        category: "residential",
        location: "Goa",
        area: "31.82 Acres",
        client: "Puravankara / Provident",
        type: "Group Housing: Highrise Apartment",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/projects/Adora De Goa.png",
        summary: "A luxury oceanfront community near Dabolim Airport, blending contemporary high-rise towers with Goan architectural vernacular and 3-side sea views."
    },
    {
        name: "POULOMI FLORIQUE",
        category: "residential",
        location: "Bangalore",
        area: "10 Acres",
        client: "POULOMI Group",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/projects/POULOMI FLORIQUE Bangalore.png",
        summary: "A 10-acre residential development with floral-themed landscape design, offering contemporary apartments with efficient floor plans."
    },
    {
        name: "DSR ELIXIR VILLAS",
        category: "villas",
        location: "Bangalore",
        area: "20 Acres",
        client: "DSR Infra Pvt. Ltd.",
        type: "Layout Development / Villa",
        status: "Completed",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/projects/DSR ELIXIR VILLAS Bangalore.jpg",
        summary: "A premium 20-acre villa community featuring independent villas with private gardens and resort-grade amenities set in a landscaped estate."
    },
    {
        name: "Arsis Dommasandra",
        category: "residential",
        location: "Bangalore",
        area: "6 Acres",
        client: "Arsis Developers",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Associate Director - GPPL",
        image: "images/projects/Arsis Dommasandra Bangalore.webp",
        summary: "A 6-acre residential project designed with modern architectural vocabulary and community-oriented amenity spaces."
    },
    {
        name: "KE Bandapura",
        category: "residential",
        location: "Bangalore",
        area: "6 Acres",
        client: "Keerthi Estates",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/projects/Keerthi Bandapura.png",
        summary: "A 6-acre development in Bandapura offering modern apartment living with well-planned unit designs and balanced community amenities."
    },
    {
        name: "Assetz Jakkur",
        category: "residential",
        location: "Jakkur, North Bangalore",
        area: "7,03,360 Sq. Ft.",
        client: "Assetz Group",
        type: "Group Housing: Highrise Apartment",
        status: "Ongoing",
        role: "Concept Construction stage Associate Director - KIPL",
        image: "images/projects/Assestz Jakur.png",
        summary: "A luxury residential tower featuring 234 units across 5 wings, designed as a functional landmark for elite gentry with premium clubhouse facilities."
    },
    {
        name: "AWHO Clubhouse",
        category: "villas",
        location: "Whitefield, Bangalore",
        area: "15,000 Sq. Ft.",
        client: "AWHO",
        type: "Club House",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/projects/AWHO - Clubhouse.png",
        summary: "Premium clubhouse facility for the Army Welfare Housing Organization featuring recreational spaces for defence families."
    },
    {
        name: "AWHO Tundup Vihar",
        category: "villas",
        location: "Mysore",
        area: "4,81,823 Sq. Ft.",
        client: "AWHO",
        type: "Layout Development / Villa",
        status: "Ongoing",
        role: "Concept Construction stage Associate Director - KIPL",
        image: "images/projects/AWHO Tundup Vihar.png",
        summary: "A 29.97-acre villa township for AWHO featuring residential plots, community buildings, and infrastructure integrated with the natural site topography."
    },
    {
        name: "Century Eden",
        category: "villas",
        location: "Bangalore",
        area: "12,00,000 Sq. Ft.",
        client: "Century",
        type: "Layout Development / Villa",
        status: "Completed",
        role: "Concept Construction stage Associate Director - KIPL",
        image: "images/projects/Century Eden.png",
        summary: "A 12-lakh sq. ft villa community emphasizing sustainability and natural harmony, with streetscapes identified by splashes of color and fragrance."
    },
    {
        name: "Amitha Wisdom Homes",
        category: "residential",
        location: "Kaggalipura, Kanakapura Road, Bengaluru",
        area: "1,85,454 Sq. Ft.",
        client: "Cadabam Group",
        type: "Senior Living / Housing",
        status: "Ongoing",
        role: "Concept Construction stage Associate Director - KIPL",
        image: "images/projects/Cadabam’s Senior Living.png",
        summary: "A barrier-free senior living development focusing on safety, accessibility, and social interaction to enrich the silver years of its residents."
    },
    {
        name: "Vedanta Township",
        category: "residential",
        location: "Lanjigarh, Odisha",
        area: "5,97,135 Sq. Ft.",
        client: "Vedanta",
        type: "Residential Township",
        status: "Ongoing",
        role: "Concept Construction stage Associate Director - KIPL",
        image: "images/projects/Vedanta Residental Township.png",
        summary: "A comprehensive residential township for Vedanta's operations, integrating architectural, structural, and landscape services."
    },
    {
        name: "Hulla Homes",
        category: "residential",
        location: "Bangalore",
        area: "2,76,000 Sq. Ft.",
        client: "Saideep Estates",
        type: "Residential Development",
        status: "Completed",
        role: "Construction stage Associate Director - KIPL",
        image: "images/projects/Saideep Estates.png",
        summary: "A residential and commercial development delivering quality urban housing and integrated services."
    },
    {
        name: "Yenepoya Family Accommodation",
        category: "residential",
        location: "Mangalore",
        area: "92,00,000 Sq. Ft.",
        client: "KEF INFRA",
        type: "Highrise Apartment (Healthcare)",
        status: "Completed",
        role: "Concept Construction stage Associate Director - KIPL",
        image: "images/projects/Family Accommodation & Boys Hostel Extension – Yenepoya University, Mangalore.png",
        summary: "India's first fully factory-made residential project, delivered in just 9 months using advanced industrialized off-site construction technology."
    },
    {
        name: "Manyata techpark",
        category: "commercial",
        location: "Nagavara, Hebbal Outer Ring Road, Bengaluru",
        area: "14,85,601 Sq. Ft.",
        client: "MFAR Holdings Pvt. Ltd.",
        type: "Commercial / IT Office Building",
        status: "Completed",
        role: "Construction stage Associate Director - KIPL",
        image: "images/projects/MFAR Manyata Tech Park.png",
        summary: "A Grade-A IGBC Gold certified commercial development featuring a 12-storey structure with modern corporate amenities."
    },
    {
        name: "SLK Green Park",
        category: "commercial",
        location: "Pujanahalli Village, Devanahalli, Bengaluru",
        area: "8,00,000 Sq. Ft.",
        client: "SLK Software",
        type: "IT Office Building",
        status: "Completed",
        role: "Concept stage Associate Director - KIPL",
        image: "images/projects/SLK Green Park.png",
        summary: "A high-tech single-tenant corporate campus on 7 acres, featuring non-uniform height wings designed with parallel thinking for innovation-driven banking and manufacturing sectors."
    },
    {
        name: "Shilpita Tech Park",
        category: "commercial",
        location: "Bangalore",
        area: "10 Acres",
        client: "Maithri Developer",
        type: "IT Office Building",
        status: "Completed",
        role: "Concept to Construction Stage Director - GPPL",
        image: "Images for Portfolio/Shilpita Tech Park Bangalore.jpg",
        summary: "A contemporary IT office building designed from concept through construction, featuring modern workspace architecture."
    },
    {
        name: "Adani Tiroda Township",
        category: "industrial",
        location: "MIDC Growth Centre, Tiroda, Maharashtra",
        area: "35 Acres",
        client: "Adani Power Maharashtra Ltd.",
        type: "Industrial Township",
        status: "Completed",
        role: "Construction stage Associate Director - KIPL",
        image: "images/projects/Adani Tiroda Township.png",
        summary: "A sustainable industrial township featuring dual plumbing, solar heating, and advanced wastewater treatment for long-term environmental conservation."
    },
    {
        name: "Model Industrial Park",
        category: "industrial",
        location: "Mehta Road, Amritsar",
        area: "132 Acres",
        client: "Alpha G - Corp",
        type: "Industrial Master Plan",
        status: "Completed",
        role: "Construction stage Associate Director - KIPL",
        image: "images/projects/Model Industrial Park.png",
        summary: "A state-of-the-art industrial development spread across 132 acres, designed for RED, ORANGE, and GREEN category industries."
    },
    {
        name: "Kalahandi Hospital",
        category: "institutional",
        location: "Bhawanipatna, Odisha",
        area: "3,96,487 Sq. Ft.",
        client: "Vedanta CSR",
        type: "Hospital",
        status: "Under Construction",
        role: "Concept to Construction stage Associate Director - KIPL",
        image: "images/projects/Kalahandi Teaching Hospital.png",
        summary: "A 200-bed fully oxygenated teaching hospital and medical college delivered as part of Vedanta's CSR initiative for the Government of Odisha."
    }
];
