/* ═══════════════════════════════════════════════════
   PROJECTS DATA — All 31 projects by Akhtar Imam
   Each project: name, category, location, area, client,
   type, status, role, image URL, summary
═══════════════════════════════════════════════════ */
const PROJECTS = [
    {
        name: "Manyata techpark",
        category: "it-office",
        location: "Bangalore",
        area: "14,00,000 Sq. Ft",
        client: "MFAR",
        type: "Commercial / IT Office Building",
        status: "Completed",
        role: "Construction Stage Associate Director - KIPL",
        image: "https://eopwebsvr.blob.core.windows.net/media/filer_public/03/58/03584bf4-77bb-4e9e-9aaf-28d6ffbe3b14/embassy_manyata_gallery_7.png",
        summary: "One of Bangalore's largest IT campuses featuring modern glass-curtain-wall corporate towers with energy-efficient façade design, accommodating thousands of IT professionals across multiple blocks."
    },
    {
        name: "SLK Green Park",
        category: "it-office",
        location: "Bangalore",
        area: "8,00,000 Sq. Ft",
        client: "SLK",
        type: "IT Office Building",
        status: "Completed",
        role: "Feasibility & Concept Associate Director - KIPL",
        image: "https://www.commercialdesignindia.com/cloud/2021/07/20/SLK-Green-Park-Bangalore-11.jpg",
        summary: "A green-certified IT office campus designed with sustainability at its core, featuring optimized floor plates, natural daylight integration, and landscaped public areas."
    },
    {
        name: "Vaishnavi IT Park",
        category: "it-office",
        location: "Bangalore",
        area: "25,00,000 Sq. Ft",
        client: "Vaishnavi Developers",
        type: "IT Office Building",
        status: "Completed",
        role: "Development for Precast Friendly Design - Associate Director - KIPL",
        image: "https://www.vaishnavigroup.com/_next/image?url=https%3A%2F%2Fvaishnavigroup-342sdf3.s3.ap-south-1.amazonaws.com%2FSAN_2503_5d6dba3c28.jpg&w=1920&q=100",
        summary: "Bangalore's 25-lakh sq. ft tech park built with precast-friendly design methodology, maximizing construction efficiency while maintaining premium architectural standards.",
        isGenesis: true
    },
    {
        name: "Shilpita Tech Park",
        category: "it-office",
        location: "Bangalore",
        area: "",
        client: "Maithri Developers",
        type: "IT Office Building",
        status: "Completed",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/it-office.png",
        summary: "A contemporary IT office building designed from concept through construction, featuring modern workspace architecture with efficient structural systems."
    },
    {
        name: "Kalahadi Teaching Hospital",
        category: "healthcare",
        location: "Bhawanipatna, Odisha",
        area: "3,96,487 Sq. Ft",
        client: "Vedanta",
        type: "Hospital",
        status: "Completed",
        role: "Construction Stage Associate Director - KIPL",
        image: "https://educationbytes.in/wp-content/uploads/2023/04/GMC-Kalahandi.jpg",
        summary: "A comprehensive 500-bed teaching hospital and medical college in Odisha, designed for institutional healthcare with advanced medical facilities, OPDs, diagnostic centers, and faculty accommodation."
    },
    {
        name: "Yenepoya Family Accommodation",
        category: "healthcare",
        location: "Mangalore",
        area: "92,000 Sq. Ft",
        client: "KEF INFRA",
        type: "Highrise Apartment (Healthcare)",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "https://odisha.gov.in/sites/default/files/2023-11/1_18.jpg",
        summary: "Family accommodation facility for hospital staff at Yenepoya Medical University, designed with precast construction technology delivering high-quality residential units efficiently."
    },
    {
        name: "Adani Tiroda Township",
        category: "masterplan",
        location: "Tiroda, Maharashtra",
        area: "35 Acres",
        client: "Adani",
        type: "Industrial Township",
        status: "Completed",
        role: "Construction Stage Associate Director - KIPL",
        image: "images/masterplan.png",
        summary: "A 35-acre integrated industrial township master plan for Adani's Tiroda power plant, featuring residential quarters, amenities, recreational facilities, and green infrastructure for plant employees."
    },
    {
        name: "Adani Kawai Township",
        category: "masterplan",
        location: "Kawai, Rajasthan",
        area: "12 Acres",
        client: "Adani",
        type: "Industrial Township",
        status: "Completed",
        role: "Construction Stage Associate Director - KIPL",
        image: "images/masterplan.png",
        summary: "A compact 12-acre self-sufficient township in Rajasthan designed for Adani's Kawai thermal power plant, incorporating climate-responsive architecture suited to the arid environment."
    },
    {
        name: "AWHO Clubhouse",
        category: "villas",
        location: "Bangalore",
        area: "45,000 Sq. Ft",
        client: "AWHO",
        type: "Club House",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/villa.png",
        summary: "Premium clubhouse facility for the Army Welfare Housing Organization featuring indoor and outdoor sports, swimming pool, banquet hall, gymnasium, and recreational spaces for defence families."
    },
    {
        name: "Adora De Goa",
        category: "residential",
        location: "Goa",
        area: "20 Acres",
        client: "Puravankara / Provident",
        type: "Group Housing: Highrise Apartment",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/residential.png",
        summary: "A 20-acre luxury residential community in Goa blending contemporary highrise towers with Goan architectural vernacular, featuring landscaped gardens and resort-style amenities."
    },
    {
        name: "The Tree",
        category: "residential",
        location: "Bangalore",
        area: "6,73,647 Sq. Ft",
        client: "Provident",
        type: "Group Housing: Highrise Apartment",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "https://im.proptiger.com/1/1410427/6/the-tree-elevation-10522037.jpeg",
        summary: "An eco-themed residential highrise with biophilic design principles, incorporating extensive greenery, vertical gardens, and nature-integrated living spaces across multiple towers.",
        isGenesis: true
    },
    {
        name: "Ozone WF 48",
        category: "residential",
        location: "Bangalore",
        area: "12,40,000 Sq. Ft",
        client: "Ozone Group",
        type: "Group Housing: Highrise Apartment",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "https://is1-2.housingcdn.com/4f2250e8/d7ac548688443eb398bd8bbc69ec173a/v0/fs/ozone_wf48-mahadevapura-bengaluru-ozone_urbana_infra_developers_private_limited.jpeg",
        summary: "A landmark 12.4-lakh sq. ft residential development in Whitefield with contemporary towers, expansive podium gardens, and premium lifestyle amenities designed for modern urban living."
    },
    {
        name: "Ozone Polestar",
        category: "residential",
        location: "Bangalore",
        area: "2,00,000 Sq. Ft",
        client: "Ozone Group",
        type: "Group Housing: Highrise Apartment",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "https://is1-2.housingcdn.com/4f2250e8/89bb12853240ea89c0b1156641ab4d95/v0/fs-large/ozone_pole_star-nagavara-bengaluru-ozone_group.jpg",
        summary: "A boutique residential highrise delivering 2 lakh sq. ft of premium apartments with thoughtful space planning, modern facades, and curated landscape design."
    },
    {
        name: "Purva Zenium",
        category: "residential",
        location: "Bangalore",
        area: "11,25,769 Sq. Ft",
        client: "Puravankara",
        type: "Group Housing: Highrise Apartment",
        status: "Completed",
        role: "Associate Director - KIPL / GPPL",
        image: "https://housing-images.n7net.in/4f2250e8/4ed28b71afe6e1a3eceb0223c31c4a0a/v0/fs-large/purva_zenium-hosahalli_karnataka_1-bengaluru-puravankara_limited.jpeg",
        summary: "Part of a 150-acre integrated lifestyle township on Airport Road featuring 12-14 towers of 12-13 floors each, emphasizing technology meeting organic and sustainable living with 80% open spaces."
    },
    {
        name: "Shimmering Heights",
        category: "residential",
        location: "Cochin",
        area: "5,21,000 Sq. Ft",
        client: "MFAR",
        type: "Group Housing: Highrise Apartment",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/residential.png",
        summary: "Cochin's premium residential highrise project spanning 5.2 lakh sq. ft, offering panoramic views, contemporary interiors, and waterfront-inspired landscape design."
    },
    {
        name: "Amitha Wisdom Homes",
        category: "residential",
        location: "Bangalore",
        area: "1,85,454 Sq. Ft",
        client: "Cadabam Group",
        type: "Senior Living / Housing",
        status: "Design",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/residential.png",
        summary: "A specialized senior living community designed with barrier-free accessibility, healthcare integration, community spaces, and age-appropriate amenities for dignified independent living."
    },
    {
        name: "Assetz Jakkur",
        category: "residential",
        location: "Bangalore",
        area: "7,03,360 Sq. Ft",
        client: "Assetz Group",
        type: "Group Housing: Highrise Apartment",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/residential.png",
        summary: "A 7-lakh sq. ft residential development in Jakkur designed with contemporary layout optimization, efficient structural systems, and premium amenity spaces including landscaped gardens."
    },
    {
        name: "AWHO Tundup Vihar",
        category: "villas",
        location: "Mysore",
        area: "4,81,823 Sq. Ft",
        client: "AWHO",
        type: "Layout Development / Villa",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/villa.png",
        summary: "A villa township for Army Welfare Housing Organization in Mysore, featuring individual villa plots with community amenities, landscaped avenues, and secure gated infrastructure."
    },
    {
        name: "Century Eden",
        category: "villas",
        location: "Bangalore",
        area: "12,00,000 Sq. Ft",
        client: "Century",
        type: "Layout Development / Villa",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/villa.png",
        summary: "A premium 12-lakh sq. ft villa community in Bangalore offering spacious independent villas with private gardens, clubhouse, and resort-style amenities in a lush green setting."
    },
    {
        name: "Vedanta Township",
        category: "masterplan",
        location: "Lanjigarh, Odisha",
        area: "5,97,135 Sq. Ft",
        client: "Vedanta",
        type: "Industrial Township",
        status: "Completed",
        role: "Concept to Construction Stage Associate Director - KIPL",
        image: "images/masterplan.png",
        summary: "An industrial township master plan for Vedanta's Lanjigarh operations in Odisha, integrating residential, commercial, and recreational zones with environmental sensitivity."
    },
    {
        name: "Hulla Homes",
        category: "residential",
        location: "Bangalore",
        area: "2,76,000 Sq. Ft",
        client: "Saideep Estates",
        type: "Residential Development",
        status: "Completed",
        role: "Construction Stage Director - GPPL",
        image: "images/residential.png",
        summary: "A residential group housing project delivering 2.76 lakh sq. ft of quality apartments, successfully managed through the construction stage with focus on timely delivery and quality."
    },
    {
        name: "DSR EVOQ",
        category: "residential",
        location: "Bangalore",
        area: "1.95 Million Sq. Ft",
        client: "DSR Infra Pvt. Ltd.",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/residential.png",
        summary: "A flagship 1.95M sq. ft residential development featuring three G+30 majestic towers with Mediterranean-inspired aesthetics, modern glass balcony railings, and premium lifestyle amenities.",
        isGenesis: true
    },
    {
        name: "ARK OAK TREE",
        category: "residential",
        location: "Bangalore",
        area: "2 Acres",
        client: "ARK",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/residential.png",
        summary: "A boutique 2-acre residential project with focus on intimate community living, featuring thoughtful unit layouts, shared green spaces, and contemporary architectural expression.",
        isGenesis: true
    },
    {
        name: "PAVANI MIRABILIA",
        category: "residential",
        location: "Bangalore",
        area: "13 Acres",
        client: "Pavani Group",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/residential.png",
        summary: "A 13-acre residential township under construction featuring multiple towers with modern design language, extensive landscape zones, and community-centric amenities.",
        isGenesis: true
    },
    {
        name: "POULOMI FLORIQUE",
        category: "residential",
        location: "Bangalore",
        area: "10 Acres",
        client: "POULOMI Group",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/residential.png",
        summary: "A 10-acre residential development with floral-themed landscape design, offering contemporary apartments with efficient floor plans and vibrant community spaces.",
        isGenesis: true
    },
    {
        name: "DSR THE ADDRESS",
        category: "residential",
        location: "Bangalore",
        area: "26 Acres",
        client: "DSR Infra Pvt. Ltd.",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/residential.png",
        summary: "A sprawling 26-acre mega residential township by DSR Infra featuring multiple towers, extensive landscape and amenity zones, and a self-contained urban ecosystem.",
        isGenesis: true
    },
    {
        name: "DSR ELIXIR VILLAS",
        category: "villas",
        location: "Bangalore",
        area: "20 Acres",
        client: "DSR Infra Pvt. Ltd.",
        type: "Layout Development / Villa",
        status: "Completed",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/villa.png",
        summary: "A premium 20-acre villa community by DSR featuring independent villas with private gardens, contemporary design, and resort-grade amenities set in a landscaped estate.",
        isGenesis: true
    },
    {
        name: "Highland Greenz",
        category: "residential",
        location: "Bangalore",
        area: "10 Acres",
        client: "DSR Infra Pvt. Ltd.",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/residential.png",
        summary: "A 10-acre green-themed residential development emphasizing sustainable design, efficient space planning, and lush landscaping for healthy community living."
    },
    {
        name: "Arsis Dommasandra",
        category: "residential",
        location: "Bangalore",
        area: "6 Acres",
        client: "Arsis Developers",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/residential.png",
        summary: "A 6-acre residential project in Dommasandra designed with modern architectural vocabulary, efficient structural grid, and community-oriented amenity spaces."
    },
    {
        name: "AVPL Kachanayakanahalli",
        category: "residential",
        location: "Bangalore",
        area: "4 Acres",
        client: "Abhee Ventures Pvt. Ltd.",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/residential.png",
        summary: "A compact 4-acre residential development with optimized building footprints, maximizing open space and greenery while delivering quality residential units."
    },
    {
        name: "KE Bandapura",
        category: "residential",
        location: "Bangalore",
        area: "6 Acres",
        client: "Keerthi Estates",
        type: "Residential Group Housing",
        status: "Under Construction",
        role: "Concept to Construction Stage Director - GPPL",
        image: "images/residential.png",
        summary: "A 6-acre residential development in Bandapura offering modern apartment living with well-planned unit designs and balanced community amenity provisions.",
        isGenesis: true
    }
];


